antiOopsCoolDownTicks: 5
# This cooldown prevents accidentally casting multiple valuable scrolls when only one use was intended.
# It is not for game balance. See [TODO: Add a meta-spell for cooldowns]

spells:
  NoOp:
    triggerItem:
      ==: org.bukkit.inventory.ItemStack
      type: SUGAR_CANE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §aNo Op Scroll
    effects:
      nop: null
  # The above example is the simplest possible spell.
  # It is a spell named NoOp that invokes the "nop" effect with no arguments.
  FancyNoOp:
    triggerItem:
      ==: org.bukkit.inventory.ItemStack
      type: SUGAR_CANE
      meta:
        ==: ItemMeta
        meta-type: UNSPECIFIC
        display-name: §aFancy No Op Scroll
    effects:
      nop:
        isFancy: true