name: civ-spell-api
version: @version@-@apitype@-@apiversion@
description: Adds an api to add spells to civcraft-type servers
authors: [Amelorate]
website: https://github.com/Ameliorate/CivSpellAPI
api-version: 1.13

depend: [CivModCore]

main: pw.amel.civspell.CivSpells

commands:
  csgiveitem:
    description: Give a player a number of the item used to triger a given spell.
    usage: /csgiveitem [player] [number] [spell (Can contain spaces)]
    permision: civ-spell-api.give
    aliases: csgive
  csreload:
    description: Reloads the config of CivSpellAPI from disk.
    usage: /csreload
    permision: civ-spell-api.reload

permisions:
  civ-spell-api.*:
    description: Gives access to all CivSpellAPI commands.
    children:
      civ-spell-api.reload: true
    civ-spell-api.reload:
      description: Reload the config from disk.
    civ-spell-api.give:
      description: Usage of the /csgiveitem
