name: civ-spell-api
version: @version@-@apitype@-@apiversion@
description: Adds an api to add spells to civcraft-type servers
authors: [Amelorate]
website: https://github.com/Ameliorate/CivSpellAPI

main: org.ame.civspell.Main

commands:
  givescroll:
    description: Give a player a number of magic scrolls. (Defaults to 1 scroll)
    usage: /givescroll [player] [spell] {number}
  csreload:
    description: Reloads the config of CivSpellAPI from disk.
    usage: /csreload
    permision: civ-spell-api.reload
    aliases: csr

permisions:
  civ-spell-api.*:
    description: Gives access to all CivSpellAPI commands.
    children:
      civ-spell-api.reload: true
    civ-spell-api.reload:
      description: Reload the config from disk.