name: civ-spell-api
version: 0.0.4-@apitype@-1.10.2-R0.1-SNAPSHOT
description: Adds an api to add spells to civcraft-type servers
authors: [Amelorate]
website: https://github.com/Ameliorate/CivSpellAPI

main: org.ame.civspell.Main

commands:
  csgivescroll:
    description: Give a player a number of magic scrolls. (Defaults to 1 scroll)
    usage: /givescroll [player] [spell] {number}
    aliases: csgs
  csreload:
    description: Reloads the config of CivSpellAPI from disk.
    usage: /csreload
    permision: civ-spell-api.reload
    aliases: csr

permisions:
  civ-spell-api.*:
    description: Gives access to all CivSpellAPI commands.
    children:
      civ-spell-api.reload: true
    civ-spell-api.reload:
      description: Reload the config from disk.
    civ-spell-api.give.*:
      description: Allows the person to use any of the commands to give scrolls and other spell related items.
      children:
        civ-spell-api.give.scroll: true
    civ-spell-api.give.scroll:
      description: Allows the player to use the /givescroll command to obtain any scroll for free.